from core.style.day_period import DayPeriod
from core.style.message_pack import MessagePack
from core.style.message_scene import MessageScene
from core.style.message_tone import MessageTone

from core.style.condition.day_period_condition import DayPeriodCondition
from core.style.condition.month_condition import MonthCondition

from core.style.condition.weekday_condition import WeekdayCondition
from core.style.condition.weekend_start_condition import WeekendStartCondition
from core.style.season import Season
from core.style.condition.season_condition import SeasonCondition

ROMANTIC_STYLE = MessagePack(
    scenes=[
        # 通用基础场景
        MessageScene(text="日子缓慢铺展，像一页被风轻轻翻动的诗。"),
        MessageScene(text="今天的光线极其温柔，正落在微小的事物上。"),
        MessageScene(text="空气里浮动着一种被拉长了的、缓慢的安静。"),
        MessageScene(text="世界正在悄悄卸下防备，变得柔软起来。"),
        MessageScene(text="长风吹过来的时候，连时间的步履都慢了下来。"),
        # 星期
        MessageScene(
            text="新的一周正悄然递来序言，愿你翻开得足够轻盈。",
            conditions=[WeekdayCondition({0})],
        ),
        MessageScene(
            text="今天的城市，似乎在空气里提前藏好了下班的松弛感。",
            conditions=[WeekdayCondition({4})],
        ),
        MessageScene(
            text="傍晚的风是个藏不住秘密的信使，一开口就在催你回家了。",
            conditions=[
                WeekdayCondition({3}),
                DayPeriodCondition({DayPeriod.DUSK, DayPeriod.EVENING}),
            ],
        ),
        MessageScene(
            text="风里已经隐隐绰绰地，有了周末那股自由的味道。",
            conditions=[WeekendStartCondition()],
        ),
        # 四季场景
        MessageScene(
            text="春天正在空气的每一个褶皱里，慢慢苏醒。",
            conditions=[SeasonCondition({Season.SPRING})],
        ),
        MessageScene(
            text="风里携着些许潮湿而柔软的泥土气，那是春天的信件。",
            conditions=[SeasonCondition({Season.SPRING})],
        ),
        MessageScene(
            text="夏天的白昼总是格外任性，把黄昏拉得无限长。",
            conditions=[SeasonCondition({Season.SUMMER})],
        ),
        MessageScene(
            text="盛夏的滚烫热意，在空气里正横冲直撞。",
            conditions=[SeasonCondition({Season.SUMMER})],
        ),
        MessageScene(
            text="风里终于舍得捎来几分秋天的清爽与克制。",
            conditions=[SeasonCondition({Season.AUTUMN})],
        ),
        MessageScene(
            text="黄昏在秋天换了更温柔的涂料，在大地上描摹得格外缓慢。",
            conditions=[SeasonCondition({Season.AUTUMN})],
        ),
        MessageScene(
            text="冬天大刀阔斧地剥离了喧嚣，让整个世界安静得像一幅画。",
            conditions=[SeasonCondition({Season.WINTER})],
        ),
        MessageScene(
            text="空气里那抹极淡的寒意，让清晨的呼吸都变得清澈。",
            conditions=[SeasonCondition({Season.WINTER})],
        ),
        # 月份场景
        MessageScene(
            text="一月的寒风里，还偷偷揉着些许未散的新年余温。",
            conditions=[MonthCondition({1})],
        ),
        MessageScene(
            text="冬天的列车，把整座城市温柔地停靠在一月的站台。",
            conditions=[MonthCondition({1})],
        ),
        MessageScene(
            text="岁月的长卷，正极其缓慢地展开新一年的第一页。",
            conditions=[MonthCondition({1})],
        ),
        MessageScene(
            text="二月的空气里，回暖的春意正在泥土下悄悄排练。",
            conditions=[MonthCondition({2})],
        ),
        MessageScene(
            text="三月是个温柔的旅人，随手把春天落在了街道中央。",
            conditions=[MonthCondition({3})],
        ),
        MessageScene(
            text="空气里的风不小心撞翻了花期，满城都是酝酿中的香气。",
            conditions=[MonthCondition({3})],
        ),
        MessageScene(
            text="春风正借着长街的掩护，在水泥森林里东奔西跑。",
            conditions=[MonthCondition({3})],
        ),
        MessageScene(
            text="五月的晚风太撩人，总让人想多绕几条街再回家。",
            conditions=[MonthCondition({5})],
        ),
        MessageScene(
            text="五月擅长用最细腻的笔触，把夜色染得毫无破绽。",
            conditions=[MonthCondition({5})],
        ),
        MessageScene(
            text="空气里漂浮着刚刚破土的、属于初夏的轻快气息。",
            conditions=[MonthCondition({5})],
        ),
        MessageScene(
            text="六月的白昼开始明目张胆地变长，向黑夜偷渡着日光。",
            conditions=[MonthCondition({6})],
        ),
        MessageScene(
            text="夏天的触角正在城市里一点点蔓延，炽热且蓬勃。",
            conditions=[MonthCondition({6})],
        ),
        MessageScene(
            text="傍晚的风卷起初夏的裙摆，带着微微发烫的试探。",
            conditions=[MonthCondition({6})],
        ),
        MessageScene(
            text="七月的半空中，到处都漂浮着盛夏揉碎了的光芒。",
            conditions=[MonthCondition({7})],
        ),
        MessageScene(
            text="无休止的蝉鸣，把整个七月吵闹得生机盎然。",
            conditions=[MonthCondition({7})],
        ),
        MessageScene(
            text="城市的夏夜，总在路灯亮起的一瞬间缓慢发亮。",
            conditions=[MonthCondition({7})],
        ),
        MessageScene(
            text="八月的晚风依旧执拗，怀里还揣着盛夏不肯放手的温度。",
            conditions=[MonthCondition({8})],
        ),
        MessageScene(
            text="黄昏在八月最容易迷路，总是耽搁了很久才肯离去。",
            conditions=[MonthCondition({8})],
        ),
        MessageScene(
            text="滚烫的夜色与不知疲倦的蝉鸣，瓜分了整个八月的梦境。",
            conditions=[MonthCondition({8})],
        ),
        MessageScene(
            text="九月的风终于学会了妥协，开始有了秋天的沉静味道。",
            conditions=[MonthCondition({9})],
        ),
        MessageScene(
            text="白昼正不露声色地变短，向夜晚交出它的疆域。",
            conditions=[MonthCondition({9})],
        ),
        MessageScene(
            text="初秋的风毫无目的，只是轻轻地把落叶吹进城市的怀抱。",
            conditions=[MonthCondition({9})],
        ),
        MessageScene(
            text="十月是个慷慨的画师，把每一个黄昏都拉得极长极远。",
            conditions=[MonthCondition({10})],
        ),
        MessageScene(
            text="风开始变得清爽，在没有人的角落里独自安静。",
            conditions=[MonthCondition({10})],
        ),
        MessageScene(
            text="秋天踩着金黄的碎屑，正在街道之间缓慢且盛大地铺开。",
            conditions=[MonthCondition({10})],
        ),
        MessageScene(
            text="十一月的夜晚开始有了锋芒，风里藏着些许微凉的叮嘱。",
            conditions=[MonthCondition({11})],
        ),
        MessageScene(
            text="空气里的温度在往下坠，那是冬日在步步靠近的足音。",
            conditions=[MonthCondition({11})],
        ),
        MessageScene(
            text="黄昏在十一月退场得极快，留下一地安静的暮色。",
            conditions=[MonthCondition({11})],
        ),
        MessageScene(
            text="十二月把城市的霓虹点亮，冷冬里的灯光总显得格外温暖。",
            conditions=[MonthCondition({12})],
        ),
        MessageScene(
            text="漫长的冬夜张开巨大的羽翼，正在缓慢拥抱整座城市。",
            conditions=[MonthCondition({12})],
        ),
        MessageScene(
            text="这一年的故事快要写到宏大的结尾了，愿你收尾得温柔。",
            conditions=[MonthCondition({12})],
        ),
    ],
    greetings={
        DayPeriod.DAWN: [
            "晨曦微茫，愿清晨对你温柔一点。",
            "天快亮了，今天也会慢慢开始。",
            "熹微的光线刚刚好，愿你今天轻盈。",
        ],
        DayPeriod.MORNING: [
            "早安，把脚步放慢一点去生活。",
            "早安，愿阳光刚好落进生活的缝隙。",
            "早安，温柔正藏在窗外的蓝天里。",
        ],
        DayPeriod.NOON: [
            "正午的光线有些饱满，记得妥妥吃饭。",
            "辛苦半天了，去看看一片云的轨迹。",
            "中午好，把视线从屏幕前短暂移开吧。",
        ],
        DayPeriod.AFTERNOON: [
            "下午茶时间，愿困倦被晚风轻轻吹散。",
            "阳光开始倾斜，适合短暂地发一会儿呆。",
            "下午辛苦了，可以稍微慢下来一点点。",
        ],
        DayPeriod.DUSK: [
            "黄昏好，日落是一天里最慷慨的温柔。",
            "晚风正在变轻，愿它替你卸下疲惫。",
            "忙碌快结束了，希望今晚有舒服的晚霞。",
        ],
        DayPeriod.EVENING: [
            "晚上好，愿夜晚的宽容安抚所有情绪。",
            "灯火初上，愿今晚的月色比日光温柔。",
            "夜色正深，愿今晚的风刚好吹散疲惫。",
        ],
        DayPeriod.LATE_NIGHT: [
            "夜已经深了，剩下的时间留给自己吧。",
            "明朝无事，愿今夜有安静而长久的梦。",
            "别太晚睡，今晚宜跌进温柔的梦乡。",
        ],
    },
    tones=[
        MessageTone(
            header="齿轮在庞大的体制中严丝合缝地转动，时间被精确地切割成按部就班的钟点。然而，当你望向窗外云朵的停顿，或是任由指尖在键盘上悬停，那一刻，宏大的秩序便出现了一道温柔的裂缝。",
            footer="那是属于你自己的时间，在精密的缝隙里偷来的一缕风，请心安理得地将它收藏。",
        ),
        MessageTone(
            header="世界的运转总是行色匆匆，催促着每一个赶路的人。但在起身的刹那，在走向茶水间的那几十步里，世界的流速似乎变慢了，咖啡的香气与晃动的水光，重组了这一刻的宇宙。",
            footer="你不是在逃避，你只是在世界的边缘，短暂地为自己的灵魂点燃一支隐秘的烟火。",
        ),
        MessageTone(
            header="写不完的报告与回不完的邮件，不过是漫长岁月里微不足道的背景噪音。当你决定去走廊尽头看一眼落日，那些堆叠的琐事便在金黄色的光芒中，退化成了无声的默片。",
            footer="把真正的心跳留给这一抹晚霞吧，在宏大的商业逻辑里，这是你最浪漫的叛逆。",
        ),
        MessageTone(
            header="写字楼的玻璃幕墙隔绝了四季的呼吸，却隔不断指尖划过桌面的慵懒。在那些故意拉长的呼吸里，你把自己从紧绷的日程表里抽离出来，像一尾游离于网罗之外的鱼。",
            footer="游向那片没有KPI的深海吧，哪怕只有几分钟，你也是自己世界里自由的岛主。",
        ),
        MessageTone(
            header="日历上的数字代表着别人的期许，而你在工位上的每一次失神、每一次伸懒腰，都是在漫长的时间长河里，为自己私垦出一块不被打扰的秘密花园。",
            footer="在这座花园里，没有催促的指令，只有你与时间的握手言和，尽情享受这片刻的荒废。",
        ),
        MessageTone(
            header="荧幕上的光斑闪烁着冰冷的逻辑，而生命的律动却藏在那些温热的间歇里。去洗手间听听水流的声音，去露台吹吹没有方向的风，世界正用这种方式提醒你它的存在。",
            footer="老板买断了八小时的产出，却买不走你对一阵风的感知，把这份感知留给自己，才是最体面的富有。",
        ),
        MessageTone(
            header="时间并不会因为密集的会议而变得更有价值，它反而在那些被故意‘浪费’的瞬间里，折射出了诗意。当你托着腮看着天花板发呆，时间的流淌便有了实体。",
            footer="让思绪无目的自由漂流吧，那些不被定义的空白，才是你对抗庸常生活最浪漫的武器。",
        ),
        MessageTone(
            header="万物都在遵循着某种既定的轨道运转，但生命的奇迹往往发生在脱轨的瞬间。在你决定站起身、离开工位、去看看远处绿植的那一刻，你就从庞大的机器中解放了自己。",
            footer="不要心怀愧疚，这短暂的停顿，是世界给所有疲惫灵魂最温柔的停靠港湾。",
        ),
        MessageTone(
            header="世界在用数字、图表和截止日期来定义你的价值，但时间的真谛其实藏在那些无法被量化的瞬间——比如一口温热的水，或者是走廊里一次无动机的漫步。",
            footer="用这些细碎的停顿去抵抗宏大的规训，在属于老板的领地上，做自己浪漫的拾荒者。",
        ),
        MessageTone(
            header="光影在办公桌上缓缓移动，像是一场无声的邀请。当你选择顺从身体的疲惫，闭上眼沉浸在几分钟的静谧中，周遭的喧嚣便如潮水般退去，只留下内心的宁静。",
            footer="世界给你的薪水是有限的，但你给自己的温柔可以无限。愿你在每个偷来的闲暇里，都能与浪漫撞个满怀。",
        ),
        MessageTone(
            header="数字在屏幕上跳动，像是一场永无止境的循环。然而当你悄悄把视线移开，去观察指尖落下的那一缕阳光，或者听听窗外掠过的鸟鸣，这串冰冷的公式便有了诗意的注解。",
            footer="在宏大的世界里，总有一些缝隙是留给浪漫的，去抓牢那一抹不属于任何人的光亮吧。",
        ),
        MessageTone(
            header="大厦的阴影随着日照缓慢倾斜，那是时间在城市里留下的脚印。当你决定按下生活的暂停键，靠在椅背上任由思绪放空，那些被拉长的阴影便成了你最安全的庇护所。",
            footer="不必总是行色匆匆，在这场漫长的白日梦里，你才是那个决定风向的人。",
        ),
        MessageTone(
            header="周遭的空气里弥漫着催促的频率，每个人都在为了某个终点奔波。而你只是静静地端起水杯，看茶叶在热气中缓缓舒展，把所有的喧嚣都隔绝在这一盏温热之外。",
            footer="让世界的流速慢下来吧，在这一刻的氤氲里，你已经赚到了最奢侈的平静。",
        ),
        MessageTone(
            header="格子间像是一个个小小的蜂巢，盛满了规律与秩序。可当你决定起身去露台，迎面撞上一阵没有目的的风时，那些用钢筋水泥筑起的边界，瞬间就坍塌成了温柔的荒野。",
            footer="风从不理会人类的日程表，它只是来邀请你，去过几分钟没有定义的生活。",
        ),
        MessageTone(
            header="键盘的敲击声此起彼伏，如同交响乐里密集的鼓点。你夹杂在这场宏大的演奏中，却悄悄转过头，看了一眼玻璃窗上倒映出的、自己嘴角那抹不易察觉的笑意。",
            footer="生活不是只有眼前的乐谱，那些偶然离调的音符，才是你送给自己最隐秘的赞美诗。",
        ),
        MessageTone(
            header="系统在不知疲倦地发出指令，把日常拆解成无数个微小的任务。但当你的目光落在桌角那株安静的绿植上，看见叶片上细小的绒毛时，生命最初的灵动便击碎了所有的机械感。",
            footer="万物都在无声地滋长，你也不必时刻紧绷，像植物一样，在阴凉处安心地舒展一下吧。",
        ),
        MessageTone(
            header="白昼的每一分钟都被赋予了实际的价值，被称重、被计算。只有在你偷偷开小差的那些瞬间，时间才恢复了它原本松散而美丽的模样，像流沙般轻盈地穿过指缝。",
            footer="不要为荒废的光阴感到抱歉，那些无法被变现的时刻，往往留存着最纯粹的灵魂。",
        ),
        MessageTone(
            header="走廊里的灯光散发着稳定的频率，延伸向每一个未知的角落。你漫无目的地在其中穿行，不为了遇见谁，也不为了递交什么，只是纯粹地享受一次与自己的散步。",
            footer="在这条短暂的路径上，没有身份的束缚，你只是一个正在收集安静的行者。",
        ),
        MessageTone(
            header="世界的洪流总是滚滚向前，裹挟着一切试图停留的脚步。但当你闭上双眼，靠在座椅上聆听自己的呼吸，整座城市的喧闹便如同潮水般退去，只剩下一片宁静的星海。",
            footer="在向世界交出满分的答卷之前，先在自己的星海里，沉溺片刻的温柔。",
        ),
        MessageTone(
            header="写字楼里的冷气总是维持着某种清醒的残酷，而生活原本的温度，却藏在你悄悄揉一揉酸痛手腕的间歇里。当你允许思绪在工位的椅背上向后倾斜五度，那些堆叠的社会身份，便开始成片地解冻。",
            footer="去和自己握手言和吧。在这几分钟的盲区里，世界不再向你索要任何标准答案。",
        ),
        MessageTone(
            header="高悬的钟表在以秒为单位，冷眼旁观着大厦里每一个严密的坐标。直到你突然决定端起水杯，看着一片茶叶在热气中做了个漫长的舒展——那一刻，你成功在时间的背面，私自签下了属于自己的名字。",
            footer="光阴本该是用来挥霍的。去那些不被量化的空白里，做一场心安理得的白日梦。",
        ),
        MessageTone(
            header="世界的流速总是太快，快到让人忘记了光线也是有重量的。当你悄悄把视线移开，去捕捉那缕落在盆栽边缘、正微微发亮的微尘时，你其实已经从宏大的规训里，偷走了一整个静止的午后。",
            footer="外界在不断计算着产出，而你正忙着收集浪漫。这才是对生活最体面的不服从。",
        ),
        MessageTone(
            header="格子间里的空气浮动着无数个催促的呼吸，像是一场停不下来的合奏。你夹杂其间，却突然选择在一声长长的吐气里给乐章按下静音，任由内心的岛屿，在喧嚣的浪潮中缓慢升起。",
            footer="不必时刻在轨道上狂奔。去旷野里吹吹风吧，哪怕只有一首歌的时间，你也是自由的。",
        ),
        MessageTone(
            header="屏幕上闪烁的每个字符，都在试图勾勒出一幅名为‘高效’的肖像。可当你停下敲击，看着自己指尖在键盘上方微微悬停的弧度，你便在这个由钢筋水泥筑起的精密迷宫里，为自己凿出了一扇开窗。",
            footer="去看一眼窗外掠过的飞鸟吧。在宏大的商业常态里，这一抹失神，是你最灵动的勋章。",
        ),
        MessageTone(
            header="每一张等待核对的表格，都是外界筑起的秩序围墙。而你只是静静地靠在长廊的栏杆上，任由远处的车流模糊成一条温柔的光带，那一刻，所有的紧绷都坍塌成了无声的默片。",
            footer="把无意义的停顿还给生命吧。在这场偷来的闲暇里，你才是那个定义风向的行者。",
        ),
        MessageTone(
            header="时间的河流在既定的河道里滚滚向前，裹挟着一切疲惫的步履。直到你决定去洗手间掬一捧凉水，感受水珠顺着皮肤滑落的刺痛与清醒，这长久的规训便被你轻轻撞开了一角。",
            footer="老板买断了八小时的产出，却买不走你对指尖温度的感知。把这份温柔留给自己，才是最体面的富有。",
        ),
        MessageTone(
            header="白昼的每一刻都在被称重、被换算成有形的价值。只有在你托着腮盯着桌角的马克杯、任由眼神失去焦点的那些瞬间，时间才恢复了它原本松散而美丽的模样，像流沙般轻盈地穿过指缝。",
            footer="不要为荒废的光阴感到抱歉。那些无法被变现的松弛，往往留存着最纯粹的灵魂。",
        ),
        MessageTone(
            header="周遭每个人都在为了某个终点而行色匆匆，让空气都染上了催促的频率。你只是静静地转过头，看着落地窗上倒映出的自己嘴角那抹不易察觉的轻笑，瞬间把整个世界的运转都拉成了慢镜头。",
            footer="生活不是只有眼前的乐谱。那些偶然离调的音符，才是你送给自己最隐秘的赞美诗。",
        ),
        MessageTone(
            header="大厦的阴影随着日照在长街上缓慢倾斜，那是时间掠过城市时的浅浅足音。当你选择在这个瞬间按下生活的暂停键，那些拉长的光影，便自动成了你最安全、最不被打扰的秘密港湾。",
            footer="不要心怀愧疚。这短暂的离线，是世界留给所有疲惫灵魂最温柔的庇护所。",
        ),
        MessageTone(
            header="日常的琐事再沉重，也请一定记得在精密的日程表里揉碎出几分钟的空白。有事没事站起身吧，去长廊里散散步，去茶水间听听水声，别总把自己框在小小的工位里。白昼的产出是外界的，但唯有这一呼一吸的频率，是真正属于你自己的生命。",
            footer="按部就班的打卡是在履行社会的契约，而那些心安理得的偷闲，才是你从宏大规训里赚回的自由。祝愿每一位浪漫的拾荒者，都能愉快地虚度每一个细碎的片刻。",
        ),
        MessageTone(
            header="写不完的字句总是催促着紧绷的神经，但请别忘了给灵魂松一松绑。试着离开工位，去廊道看看光影的移动，去洗手间掬一捧清凉的水。我们不必永远当这栋大厦里严丝合缝的齿轮，别忘了，生活的发球权始终握在你自己的手里。",
            footer="在属于他人的领地上，每一次短暂的‘离线’，都是你最体面的主权宣示。愿你在这场漫长的白日梦里，每天都能偷渡到最奢侈的快乐。",
        ),
        MessageTone(
            header="工作是无止境的循环，但生命的奇迹往往发生在脱轨的刹那。别老是在椅子上和疲惫死磕，起身去走走吧，哪怕只是去倒一杯温水，或者在窗前看一朵云的停顿。大厦的价值由数字定义，而你生命的价值，藏在那些无法被量化的舒展里。",
            footer="帮世界运转是职责，而偷偷开小差则是你送给自己最隐秘的赞美诗。愿天下所有不甘平庸的灵魂，都能在每个偷来的闲暇里，过得轻盈且快活。",
        ),
        MessageTone(
            header="格子间像是一个个规律的蜂巢，盛满了秩序，但也容易困住鲜活的呼吸。觉得累了的时候，就大方地站起来去露台吹吹长风，去角落里收集一阵安静。世界的洪流再滚滚向前，也买不走你对一个午后的感知，好好爱护那个正在努力生活的自己。",
            footer="既然白昼的终点都是为了碎银几两，那摸鱼时的那抹惬意，就是你最丰厚的额外犒赏。愿你每天都能在紧绷的日常里，撞进一个温柔的荒野。",
        ),
        MessageTone(
            header="屏幕上的指标闪烁着冰冷的逻辑，而生命的律动却藏在那些温热的间歇里。不要在工位上把自己坐成一尊雕塑，多去长廊里漫无目的地走两圈吧。外界给你的薪水永远有一个数字的上限，但你留给自己的温柔，本该无限辽阔。",
            footer="上班是把时间借给别人，而放空则是把生活还给自己。愿每一个在写字楼里秘密出逃的你，都能心安理得地享用每一分钟的荒废。",
        ),
        MessageTone(
            header="指令此起彼伏，把日子拆解得支离破碎。可当你决定按下暂停键，起身离开那方寸屏幕，走向不被打扰的廊道时，那些由钢筋水泥筑起的边界就瞬间瓦解了。别总在同一个地方紧绷着，要学会在阴凉处安心地舒展羽翼。",
            footer="在这场关于效率的赛跑里，偶尔停下来看看指尖的微光，才是最浪漫的叛逆。最后，祝愿所有懂得爱护自己的同行人，都能愉快地渡过每一天。",
        ),
        MessageTone(
            header="周遭的空气里弥漫着催促的频率，但你大可不必永远踩在别人的鼓点上。站起身吧，去洗手间听听水流，去阳台迎面撞一阵没有目的的风。不要为一时的失神感到内疚，保全内心的长风与安宁，比什么都重要。",
            footer="外界计算的是你的产出，而你在长廊里留下的脚印，才是生活最纯粹的注解。祝天下所有正在拯救疲惫灵魂的你我，都能快乐地虚度光阴。",
        ),
        MessageTone(
            header="键盘的敲击声像是永无止境的交响，但偶尔离调的音符才最动听。别总把自己死死钉在座椅上，有事没事去长街窗前看一眼车流，去廊道里和自己散个步。外界可以买断你当下的时间，却买不走你对一阵晚风、一抹晚霞的向往。",
            footer="在这座由数据构筑的围城里，做自己浪漫的拾荒者吧，去捡拾那些不属于任何人的平静。愿你每个偷来的闲暇，都能与愉快撞个满怀。",
        ),
        MessageTone(
            header="每一张报表都在试图称重你的这一天，而你明白，真正属于你自己的生活从来不会被写进总结里。觉得困顿了，就立刻站起来拍拍衣角，去茶水间闻闻咖啡的香气。请心安理得地为自己私垦出一块秘密花园，别老在工位里消耗了生命力。",
            footer="用这些细碎的停顿去化解宏大的规训，在既定的世界里，你才是那个决定风向的岛主。祝所有懂得在缝隙里呼吸的人，都能拥有被温柔包裹的每一天。",
        ),
    ],
)
